AllCops:
  NewCops: enable

Metrics/ClassLength:
  Max: 1500

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Enabled: false


Metrics/PerceivedComplexity:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
