name: Manual workflow
on: workflow_dispatch

jobs:
  check:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - run: |
        git fetch origin
        DATE=$(date '+%Y-%m-%d')
        BRANCH="dependabot-$DATE"
        git checkout -b $BRANCH &> /dev/null

        gh pr list --app dependabot | cut -f3 | while read branch
        do
          git pull origin $branch
        done

        git push origin $BRANCH
        gh pr create --title "Dependabot $DATE" --body "Contains all dependabot PRs from $DATE" || exit 0

        echo "Pushing to staging"
        git checkout staging &> /dev/null || git switch -c staging origin/staging &> /dev/null
        git pull origin staging &> /dev/null
        git merge $BRANCH
        git push origin staging
