name: Manual workflow
on: workflow_dispatch

jobs:
  check:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        gh pr list
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - run: |
        git checkout -b some-branch
        echo "foo" > some-file
        git add .
        git commit -m "Foo"
        gh pr create --title "Foo" --body "Foo"
