name: Manual workflow
on: [workflow_dispatch, push]

jobs:
  check:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Integrate dependabot PRs
      run: |
        git fetch --all --unshallow
        git checkout main
        DATE=$(date '+%Y-%m-%d')
        BRANCH="dependabot-$DATE"
        git checkout -b $BRANCH

        gh pr list --app dependabot | cut -f3 | while read branch
        do
          git pull --no-ff --no-edit origin $branch
        done

        git push origin $BRANCH
        gh pr create --title "Dependabot $DATE" --body "Contains all dependabot PRs from $DATE" || exit 0

        echo "Pushing to staging"
        git checkout -b staging
        git pull --no-ff --no-edit origin staging &> /dev/null || echo "Staging branch does not exist yet"
        git merge --no-ff --no-edit $BRANCH
        git push origin staging
